-- ============================================================
-- No-Code UI Builder  |  DDL – 테이블 정의
-- prefix: TB_PFCM_
-- ============================================================

-- ──────────────────────────────────────────
-- [1] UI 컴포넌트 마스터
-- ──────────────────────────────────────────
CREATE TABLE TB_PFCM_UI_CMP_M (
    UI_CMP_ID            VARCHAR(32)   NOT NULL,
    CMP_GRP_ID           VARCHAR(50)   NOT NULL,
    CMP_KD_CD            VARCHAR(50)   NOT NULL,
    CMP_WDTH_DVAL_CNTN   INTEGER       NOT NULL,
    CMP_HGHT_DVAL_CNTN   INTEGER       NOT NULL,
    -- 시스템 컬럼
    DATA_INPS_ID         VARCHAR(50)   NULL,
    DATA_INPT_DTTM       TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_INPT_PGM_ID     VARCHAR(50)   NULL,
    DATA_MFPN_ID         VARCHAR(50)   NULL,
    DATA_UPD_DTTM        TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_UPD_PGM_ID      VARCHAR(50)   NULL,
    CONSTRAINT PK_TB_PFCM_UI_CMP_M PRIMARY KEY (UI_CMP_ID)
);

COMMENT ON TABLE  TB_PFCM_UI_CMP_M                     IS 'UI 컴포넌트 마스터';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.UI_CMP_ID           IS 'UI컴포넌트ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.CMP_GRP_ID          IS '컴포넌트그룹ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.CMP_KD_CD           IS '컴포넌트유형코드';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.CMP_WDTH_DVAL_CNTN  IS '컴포넌트너비기본값내용';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.CMP_HGHT_DVAL_CNTN  IS '컴포넌트높이기본값내용';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.DATA_INPS_ID        IS '데이터입력자ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.DATA_INPT_DTTM      IS '데이터입력일시';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.DATA_INPT_PGM_ID    IS '데이터입력프로그램ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.DATA_MFPN_ID        IS '데이터수정자ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.DATA_UPD_DTTM       IS '데이터수정일시';
COMMENT ON COLUMN TB_PFCM_UI_CMP_M.DATA_UPD_PGM_ID     IS '데이터수정프로그램ID';


-- ──────────────────────────────────────────
-- [2] UI 컴포넌트 속성 마스터
-- ──────────────────────────────────────────
CREATE TABLE TB_PFCM_UI_CMP_ATTR_M (
    UI_CMP_ATTR_ID       VARCHAR(32)   NOT NULL,
    UI_CMP_ID            VARCHAR(32)   NOT NULL,
    ATTR_NM              VARCHAR(50)   NOT NULL,
    ATTR_CLSS_CD         VARCHAR(20)   NOT NULL,
    ATTR_DATA_KD_CD      VARCHAR(20)   NOT NULL,
    ATTR_CNTL_KD_CD      VARCHAR(20)   NOT NULL,
    -- 시스템 컬럼
    DATA_INPS_ID         VARCHAR(50)   NULL,
    DATA_INPT_DTTM       TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_INPT_PGM_ID     VARCHAR(50)   NULL,
    DATA_MFPN_ID         VARCHAR(50)   NULL,
    DATA_UPD_DTTM        TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_UPD_PGM_ID      VARCHAR(50)   NULL,
    CONSTRAINT PK_TB_PFCM_UI_CMP_ATTR_M PRIMARY KEY (UI_CMP_ATTR_ID),
    CONSTRAINT FK_CMP_ATTR_M_CMP_M      FOREIGN KEY (UI_CMP_ID) REFERENCES TB_PFCM_UI_CMP_M (UI_CMP_ID)
);

COMMENT ON TABLE  TB_PFCM_UI_CMP_ATTR_M                      IS 'UI 컴포넌트 속성 마스터';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.UI_CMP_ATTR_ID       IS 'UI컴포넌트속성ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.UI_CMP_ID            IS 'UI컴포넌트ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.ATTR_NM              IS '속성명';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.ATTR_CLSS_CD         IS '속성분류코드 (COMMON/SPECIFIC)';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.ATTR_DATA_KD_CD      IS '속성데이터유형코드 (STRING/NUMBER/BOOLEAN/ENUM/JSON)';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.ATTR_CNTL_KD_CD      IS '속성컨트롤유형코드 (TEXT/NUMBER/SELECT/TOGGLE/COLOR/TEXTAREA)';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.DATA_INPS_ID         IS '데이터입력자ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.DATA_INPT_DTTM       IS '데이터입력일시';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.DATA_INPT_PGM_ID     IS '데이터입력프로그램ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.DATA_MFPN_ID         IS '데이터수정자ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.DATA_UPD_DTTM        IS '데이터수정일시';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_M.DATA_UPD_PGM_ID      IS '데이터수정프로그램ID';


-- ──────────────────────────────────────────
-- [3] UI 컴포넌트 속성 상세
-- ──────────────────────────────────────────
CREATE TABLE TB_PFCM_UI_CMP_ATTR_D (
    UI_CMP_ATTR_DETL_ID  VARCHAR(32)   NOT NULL,
    UI_CMP_ATTR_ID       VARCHAR(32)   NOT NULL,
    ATTR_DETL_VLUE_CNTN  VARCHAR(50)   NOT NULL,
    SNO                  INTEGER       NOT NULL,
    -- 시스템 컬럼
    DATA_INPS_ID         VARCHAR(50)   NULL,
    DATA_INPT_DTTM       TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_INPT_PGM_ID     VARCHAR(50)   NULL,
    DATA_MFPN_ID         VARCHAR(50)   NULL,
    DATA_UPD_DTTM        TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_UPD_PGM_ID      VARCHAR(50)   NULL,
    CONSTRAINT PK_TB_PFCM_UI_CMP_ATTR_D  PRIMARY KEY (UI_CMP_ATTR_DETL_ID),
    CONSTRAINT FK_CMP_ATTR_D_ATTR_M       FOREIGN KEY (UI_CMP_ATTR_ID) REFERENCES TB_PFCM_UI_CMP_ATTR_M (UI_CMP_ATTR_ID)
);

COMMENT ON TABLE  TB_PFCM_UI_CMP_ATTR_D                         IS 'UI 컴포넌트 속성 상세';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.UI_CMP_ATTR_DETL_ID     IS 'UI컴포넌트속성상세ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.UI_CMP_ATTR_ID          IS 'UI컴포넌트속성ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.ATTR_DETL_VLUE_CNTN     IS '속성상세값내용';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.SNO                     IS '정렬순서';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.DATA_INPS_ID            IS '데이터입력자ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.DATA_INPT_DTTM          IS '데이터입력일시';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.DATA_INPT_PGM_ID        IS '데이터입력프로그램ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.DATA_MFPN_ID            IS '데이터수정자ID';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.DATA_UPD_DTTM           IS '데이터수정일시';
COMMENT ON COLUMN TB_PFCM_UI_CMP_ATTR_D.DATA_UPD_PGM_ID         IS '데이터수정프로그램ID';


-- ──────────────────────────────────────────
-- [4] UI 화면 마스터
-- ──────────────────────────────────────────
CREATE TABLE TB_PFCM_UI_SCRN_M (
    UI_SCRN_ID           VARCHAR(32)   NOT NULL,
    UI_SCRN_NM           VARCHAR(50)   NOT NULL,
    ACTV_VER_NO          INTEGER       NOT NULL DEFAULT 1,
    USE_YN               VARCHAR(1)    NOT NULL DEFAULT 'Y',
    -- 시스템 컬럼
    DATA_INPS_ID         VARCHAR(50)   NULL,
    DATA_INPT_DTTM       TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_INPT_PGM_ID     VARCHAR(50)   NULL,
    DATA_MFPN_ID         VARCHAR(50)   NULL,
    DATA_UPD_DTTM        TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_UPD_PGM_ID      VARCHAR(50)   NULL,
    CONSTRAINT PK_TB_PFCM_UI_SCRN_M PRIMARY KEY (UI_SCRN_ID)
);

COMMENT ON TABLE  TB_PFCM_UI_SCRN_M                     IS 'UI 화면 마스터';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.UI_SCRN_ID          IS 'UI화면ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.UI_SCRN_NM          IS 'UI화면명';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.ACTV_VER_NO         IS '활성화버전번호';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.USE_YN              IS '사용여부';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.DATA_INPS_ID        IS '데이터입력자ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.DATA_INPT_DTTM      IS '데이터입력일시';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.DATA_INPT_PGM_ID    IS '데이터입력프로그램ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.DATA_MFPN_ID        IS '데이터수정자ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.DATA_UPD_DTTM       IS '데이터수정일시';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_M.DATA_UPD_PGM_ID     IS '데이터수정프로그램ID';


-- ──────────────────────────────────────────
-- [5] UI 화면 컴포넌트 상세
-- ──────────────────────────────────────────
CREATE TABLE TB_PFCM_UI_SCRN_CMP_D (
    UI_SCRN_CMP_ID       VARCHAR(32)   NOT NULL,
    UI_SCRN_ID           VARCHAR(32)   NOT NULL,
    UI_CMP_ID            VARCHAR(32)   NOT NULL,
    CMP_FLD_ID           VARCHAR(50)   NOT NULL,
    HPOS_CMP_FLD_ID      VARCHAR(50)   NULL,
    XS_CRDN_VLUE_CNTN   INTEGER       NOT NULL DEFAULT 0,
    YS_CRDN_VLUE_CNTN   INTEGER       NOT NULL DEFAULT 0,
    XS_LEN_VLUE_CNTN    INTEGER       NOT NULL DEFAULT 0,
    YS_LEN_VLUE_CNTN    INTEGER       NOT NULL DEFAULT 0,
    EVET_JSON_CNTN       JSONB         NULL,
    SPEC_JSON_CNTN       JSONB         NULL,
    -- 시스템 컬럼
    DATA_INPS_ID         VARCHAR(50)   NULL,
    DATA_INPT_DTTM       TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_INPT_PGM_ID     VARCHAR(50)   NULL,
    DATA_MFPN_ID         VARCHAR(50)   NULL,
    DATA_UPD_DTTM        TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_UPD_PGM_ID      VARCHAR(50)   NULL,
    CONSTRAINT PK_TB_PFCM_UI_SCRN_CMP_D  PRIMARY KEY (UI_SCRN_CMP_ID),
    CONSTRAINT FK_SCRN_CMP_D_SCRN_M       FOREIGN KEY (UI_SCRN_ID) REFERENCES TB_PFCM_UI_SCRN_M (UI_SCRN_ID),
    CONSTRAINT FK_SCRN_CMP_D_CMP_M        FOREIGN KEY (UI_CMP_ID)  REFERENCES TB_PFCM_UI_CMP_M  (UI_CMP_ID)
);

COMMENT ON TABLE  TB_PFCM_UI_SCRN_CMP_D                         IS 'UI 화면 컴포넌트 상세';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.UI_SCRN_CMP_ID         IS 'UI화면컴포넌트ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.UI_SCRN_ID             IS 'UI화면ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.UI_CMP_ID              IS 'UI컴포넌트ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.CMP_FLD_ID             IS '컴포넌트필드ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.HPOS_CMP_FLD_ID        IS '상위컴포넌트필드ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.XS_CRDN_VLUE_CNTN      IS 'X축좌표값내용';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.YS_CRDN_VLUE_CNTN      IS 'Y축좌표값내용';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.XS_LEN_VLUE_CNTN       IS 'X축너비값내용';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.YS_LEN_VLUE_CNTN       IS 'Y축너비값내용';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.EVET_JSON_CNTN         IS '이벤트JSON내용';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.SPEC_JSON_CNTN         IS '스펙JSON내용';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.DATA_INPS_ID           IS '데이터입력자ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.DATA_INPT_DTTM         IS '데이터입력일시';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.DATA_INPT_PGM_ID       IS '데이터입력프로그램ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.DATA_MFPN_ID           IS '데이터수정자ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.DATA_UPD_DTTM          IS '데이터수정일시';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_CMP_D.DATA_UPD_PGM_ID        IS '데이터수정프로그램ID';


-- ──────────────────────────────────────────
-- [6] UI 화면 이력
-- ──────────────────────────────────────────
CREATE TABLE TB_PFCM_UI_SCRN_H (
    UI_SCRN_HIST_ID      VARCHAR(32)   NOT NULL,
    UI_SCRN_ID           VARCHAR(32)   NOT NULL,
    VER_NO               INTEGER       NOT NULL,
    SCRN_JSON_CNTN       JSONB         NOT NULL,
    FRST_STRG_DTTM       TIMESTAMP     NOT NULL DEFAULT NOW(),
    -- 시스템 컬럼
    DATA_INPS_ID         VARCHAR(50)   NULL,
    DATA_INPT_DTTM       TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_INPT_PGM_ID     VARCHAR(50)   NULL,
    DATA_MFPN_ID         VARCHAR(50)   NULL,
    DATA_UPD_DTTM        TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_UPD_PGM_ID      VARCHAR(50)   NULL,
    CONSTRAINT PK_TB_PFCM_UI_SCRN_H   PRIMARY KEY (UI_SCRN_HIST_ID),
    CONSTRAINT FK_SCRN_H_SCRN_M        FOREIGN KEY (UI_SCRN_ID) REFERENCES TB_PFCM_UI_SCRN_M (UI_SCRN_ID)
);

COMMENT ON TABLE  TB_PFCM_UI_SCRN_H                      IS 'UI 화면 이력';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.UI_SCRN_HIST_ID      IS 'UI화면이력ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.UI_SCRN_ID           IS 'UI화면ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.VER_NO               IS '버전번호';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.SCRN_JSON_CNTN       IS '화면JSON내용';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.FRST_STRG_DTTM       IS '최초저장일시';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.DATA_INPS_ID         IS '데이터입력자ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.DATA_INPT_DTTM       IS '데이터입력일시';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.DATA_INPT_PGM_ID     IS '데이터입력프로그램ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.DATA_MFPN_ID         IS '데이터수정자ID';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.DATA_UPD_DTTM        IS '데이터수정일시';
COMMENT ON COLUMN TB_PFCM_UI_SCRN_H.DATA_UPD_PGM_ID      IS '데이터수정프로그램ID';
